version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=shopping
    network_mode: bridge