Env: "dev"

DatabaseSettings:
  DatabaseURI: "root:my-secret-pw@tcp(localhost)/shopping?charset=utf8mb4&parseTime=True&loc=Local"
  DatabaseName: "shoppin"
  Username: "root"
  Password: "my-secret-pw"

NewRelicSettings:
  LicenseKey: "YOUR_LICENSE_KEY"
  AppName: "YOUR_APP_NAME"